image: node:8.11.1

pages:
  cache:
    paths:
    - ./node_modules/

  stage: deploy
  script:
  - npm install
  - CI=false npm run build
  - mv --backup=numbered build/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - dev
